### PR TITLE
Add DE Africa Landsat 8 and 9 GeoMAD example notebook

### PR DESCRIPTION
**Pull request by vikineema**
- The  `notebooks/stac-load-ls8-ls9-geomad-deafrica.py` is an example notebook  showing how to load the DE Africa Landsat 8 and Landsat 9 GeoMAD product using `odc-stac`. 
- The notebook makes use of the the `deafrica_tools` package from  https://test.pypi.org/project/testing-deafrica-tools/ . I will update the installation cell once  `deafrica_tools` is published on PyPI. 
- The `notebooks/get_product_config.py` contains the `get_product_config` function that makes it simpler for people to set up the "config" for DE Africa products.

### CODE REVIEW

**Comment by alexgleith** [comment]
Hey @vikineema two things we can improve.

1. Please use the `get_product_config` function in the Sentinel-2 example too
2. I don't think we should install DE Africa tools here. Can we please look into producing an example that works without that extra dependency.

**Comment by vikineema** [comment]
> Hey @vikineema two things we can improve.
> 
>     1. Please use the `get_product_config` function in the Sentinel-2 example too
> 
>     2. I don't think we should install DE Africa tools here. Can we please look into producing an example that works without that extra dependency.

@alexgleith In the latest commits, I updated the  `get_product_config`  function and added it to the Sentinel-2 example. I also removed the use of `deafrica-tools` from the Landsat 8-9 GeoMAD example.

**Review by caitlinadams — COMMENTED** [review]
Thank you for submitting this pull request @vikineema, I appreciate the generation of the more complex example for Digital Earth Africa, as well as a higher-level function for generating the config. 

Having reviewed the additions you've made, I'm wondering whether the best place for this documentation (and support function) is the Digital Earth Africa docs and tools? Specifically, I'm thinking that this is a great guide that Digital Earth Africa can provide to instruct users on leveraging the STAC to load data outside of the sandbox. This would be a great how-to-guide to sit alongside information about direct access (https://docs.digitalearthafrica.org/en/latest/platform_tools/access.html#spatio-temporal-asset-catalog-stac).

While we do have a Digital Earth Africa example in this repository, it's more to serve as a comparison to the two other S2 notebook examples. All three examples explicitly list the config, which may help users learn by example. My thought is that the `get_product_config` function is specifically tailored to DE Africa and DE Australia, and as such, does not belong neatly in an ODC repository. 

I can see two paths forward:
- Move this example to the DE Africa docs repository as a more complex example of how to leverage DE Africa's stac, and include the `get_product_config` function in deafrica tools
- Work with @Kirill888 to generalise the `get_product_config` function so it can be used for all STAC sources, and then incorporate the function into the `odc-stac` package, and update all three examples in this repo to use it.  

@Kirill888 -- what do you think about having a helper function to automatically generate config dictionaries? Is this something you see the need for in this package? I'm also curious about your thoughts on how we should curate the examples.

Awesome work, @vikineema -- I'm sure we'll find a good home for it!

**Comment by Kirill888** [comment]
Hi @vikineema thank you for this PR and sorry for not responding earlier, I was too preoccupied with the release...

I tend to agree with @caitlinadams on this. While this is useful information for users of DE Africa, it might be too DE Africa specific to be included in the documentation for `odc-stac` library itself. We already have notebook contributed by Caitlin that highlights the most "gotcha" aspect of working with DE Africa data, it being the configuration for S3 access for Capetown buckets. And since DE Africa already has a place for documentation like this, it's best to publish it there. We can update current sample notebook with a link to your work, once it's published, as a kind of "to explore more about working with DE Africa datasets using STAC see {this external notebook}". 

re:
> Work with @Kirill888 to generalise the get_product_config function so it can be used for all STAC sources, and then incorporate the function into the odc-stac package, and update all three examples in this repo to use it.

I think `odc-stac` should have user editable configuration that sits on disk that can be matched to any given collection as an alternative to supplying it directly at call time. Even in the ideal world, where all collections include all the necessary extensions it can still be useful for defining custom band aliases. With that mechanism in place we can also maintain a library of "known collections". It should be relatively straightforward to implement, only issue I can see is collection names clashing across different STAC API endpoints: `odc.stac.lad` can't tell precisely what data source was used to obtain STAC items in a general case, so can't use api endpoint for disambiguation of two different `sentinel-2` collections.

**Comment by vikineema** [comment]
@Kirill888 @caitlinadams Thank you for your comments. I'll close this PR and move the function into `deafrica-tools` and the example notebook into the Direct access section of the Digital Earth Africa docs. For the user-editable configuration file, can this be a `.json` file?

**Pull request closed without merging**
