### PR TITLE
Fix(load) : with "auto" chunks and type specified #181

### PR DESCRIPTION
**Pull request by nkarasiak**
Fixes issue #181 #184 and #183

### CODE REVIEW

**Comment by nkarasiak** [comment]
Hy there. 
I fix an issue with chunks "auto" with dtypes and fix cicd issues too (mypy and wheels error). 

Can someone make a feedback ? Thanks for your work 🤗 
@Kirill888 @alexgleith @robbibt

**Comment by Kirill888** [comment]
@nkarasiak thank you for the contribution, but I have to ask you to undo all the formatting changes please, and also rebase your history into a cleaner set of commits, 21 commits for fixing 3 problems is too many commits. Ideally I'd like to see only changes related to the fix present in the PR. This repo uses `black` for formatting, not `ruff` (`ruff` didn't exist when this was started). Please also remove version bump commit. In general please limit amount of change, especially various "cleanup" changes as they make it harder to understand what the real fix is. For example, I see you made various mypy fixes for dtype annotations, I can't tell if these were needed to fix CI/CD or just there as general improvement.

Right now we are in process of splitting `odc/loader/` into a separate package, so it's really important to minimize non-essential changes to the code.

**Comment by nkarasiak** [comment]
Hello @Kirill888,

Thank you for the feedback and for the explanation on how to improve my contribution. That seems really obvious when you explain it ! I'll do that in two weeks.

**Comment by nkarasiak** [comment]
I close this pull request, too much drafts.

**Pull request closed without merging**
